export const interestSeedList = [
  "Web Development",
  "Mobile Development",
  "Open Source",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Cybersecurity",
  "UI/UX Design",
  "Cloud Computing",
  "DevOps",
  "Game Development",
  "Blockchain",
  "Internet of Things (IoT)",
  "Augmented Reality",
  "Virtual Reality",
  "Software Engineering",
  "Digital Marketing",
  "Graphic Design",
  "Product Management",
  "Entrepreneurship",
  "Startups",
  "Project Management",
  "E-commerce",
  "Tech Blogging",
  "Public Speaking",
  "Photography",
  "Video Editing",
  "Finance & Investing",
  "Health Tech",
  "EdTech",
  "Clean Energy",
  "Social Impact",
  "Freelancing",
  "Remote Work",
  "Career Growth",
  "Personal Development",
  "Reading",
  "Writing",
  "Mentorship"
]
