export const skillSeedList = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "PHP",
  "Laravel",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "Git",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "REST API",
  "GraphQL",
  "Figma",
  "UI/UX Design",
  "Agile",
  "Scrum",
  "DevOps",
  "Machine Learning",
  "Data Analysis",
  "Linux",
  "Bash",
  "CI/CD",
  "Go (Golang)",
  "Ruby",
  "Rust",
  "Swift",
  "Kotlin",
  "Dart",
  "C++",
  "Solidity",
  "Vue.js",
  "Svelte",
  "WebAssembly (Wasm)",
  "Gatsby.js",
  "Angular",
  "JQuery",
  "Ruby on Rails",
  "Kafka",
  "RabbitMQ",
  "ASP.NET Core",
  "Redis",
  "Cassandra",
  "Elasticsearch",
  "Data Warehousing",
  "ETL (Extract, Transform, Load)",
  "MySQL",
  "Oracle DB",
  "Firebase",
  "Data Modeling",
  "Terraform",
  "Ansible",
  "Chef",
  "Serverless Computing (e.g., AWS Lambda, Azure Functions, Google Cloud Functions)",
  "Networking Fundamentals",
  "Jenkins",
  "GitLab CI/CD",
  "Azure DevOps",
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter (Dart)",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Deep Learning",
  "Big Data Technologies (e.g., Hadoop, Spark)",
  "R Programming",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Data Visualization",
  "Statistical Analysis",
  "Cybersecurity Fundamentals",
  "Penetration Testing",
  "Identity and Access Management (IAM)",
  "Network Security",
  "Vulnerability Assessment",
  "Blockchain",
  "Smart Contracts",
  "Decentralized Applications (DApps)",
  "Adobe XD",
  "Sketch",
  "User Research",
  "Wireframing",
  "Prototyping",
  "Kanban",
  "Jira",
  "Confluence",
  "Public Speaking",
  "Technical Writing",
  "Active Listening",
  "Cross-functional Collaboration",
  "Negotiation",
  "Analytical Thinking",
  "Root Cause Analysis",
  "Decision Making",
  "Innovation",
  "Mentorship",
  "Team Leadership",
  "Project Management",
  "Conflict Resolution",
  "Delegation",
  "Adaptability",
  "Time Management",
  "Stress Management",
  "Growth Mindset",
  "Emotional Intelligence",
  "Networking",
  "Presentation Skills",
  "Customer Service",
  "Problem Solving",
  "Critical Thinking",
  "Communication (Written & Verbal)",
  "Teamwork",
  "Attention to Detail",
  "Creativity",
  "Research Skills"
]

export const newSkillsList = [
  "Go (Golang)",
  "Ruby",
  "Rust",
  "Swift",
  "Kotlin",
  "Dart",
  "C++",
  "Solidity",
  "Vue.js",
  "Svelte",
  "WebAssembly (Wasm)",
  "Gatsby.js",
  "Angular",
  "JQuery",
  "Ruby on Rails",
  "Kafka",
  "RabbitMQ",
  "ASP.NET Core",
  "Redis",
  "Cassandra",
  "Elasticsearch",
  "Data Warehousing",
  "ETL (Extract, Transform, Load)",
  "MySQL",
  "Oracle DB",
  "Firebase",
  "Data Modeling",
  "Terraform",
  "Ansible",
  "Chef",
  "Serverless Computing (e.g., AWS Lambda, Azure Functions, Google Cloud Functions)",
  "Networking Fundamentals",
  "Jenkins",
  "GitLab CI/CD",
  "Azure DevOps",
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter (Dart)",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Deep Learning",
  "Big Data Technologies (e.g., Hadoop, Spark)",
  "R Programming",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Data Visualization",
  "Statistical Analysis",
  "Cybersecurity Fundamentals",
  "Penetration Testing",
  "Identity and Access Management (IAM)",
  "Network Security",
  "Vulnerability Assessment",
  "Blockchain",
  "Smart Contracts",
  "Decentralized Applications (DApps)",
  "Adobe XD",
  "Sketch",
  "User Research",
  "Wireframing",
  "Prototyping",
  "Kanban",
  "Jira",
  "Confluence",
  "Public Speaking",
  "Technical Writing",
  "Active Listening",
  "Cross-functional Collaboration",
  "Negotiation",
  "Analytical Thinking",
  "Root Cause Analysis",
  "Decision Making",
  "Innovation",
  "Mentorship",
  "Team Leadership",
  "Project Management",
  "Conflict Resolution",
  "Delegation",
  "Adaptability",
  "Time Management",
  "Stress Management",
  "Growth Mindset",
  "Emotional Intelligence",
  "Networking",
  "Presentation Skills",
  "Customer Service",
  "Problem Solving",
  "Critical Thinking",
  "Communication (Written & Verbal)",
  "Teamwork",
  "Attention to Detail",
  "Creativity",
  "Research Skills"
]
