name: (Oryx Build) - Deploy Node.js app to Azure Web App via Source.

on:
  push:
    # Change to the branch you want this to deploy from
    branches:
      - development 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for Azure login
      contents: read # Required for checkout

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DAEA6198291B481F8340A14BD117AE2D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4ACE3ADD494E41DD9BCDC80EB9CC5D2F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B5F0DB926AC94222A04BE549500D6953 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'etl-spark-dev'
          slot-name: 'Production'
          package: . # Deploy current directory (source code)

    # NO BUILD JOB NEEDED (or remove build steps from existing job)
    # NO ARTIFACT UPLOAD/DOWNLOAD NEEDED
