export enum NotificationEvent {
  CHAT_INVITE = "chat_invite",
  NEW_CONNECTION = "new_connection",
  CONNECTION_ACCEPTED = "accept_connection",
  UPDATE_TASK = "update_task",
  TASK_ASSIGNED = "task_assigned",
  TASK_COMMENTED = "task_commented",
  PROJECT_INVITE = "project_invite",
  POST_LIKE = "post_like",
  POST_COMMENT = "post_comment",
  MENTION_IN_COMMENT = "mention_in_comment",
  COMMUNITY_REQUEST = "community_request",
  JOIN_INVITE_EMAIL = "join_invite_email",
  ADMIN_NEW_COMMUNITY_REQUEST = "admin_new_community_request",
  COMMUNITY_REQUEST_ACCEPTED = "community_request_accepted",
  COMMUNITY_REQUEST_REJECTED = "community_request_rejected",
  FEEDBACK_SUBMITTED = "feedback_submitted",
  NEW_FEEDBACK_ADMIN = "new_feedback_admin",
  CONTACT_US_SUBMITTED = "contact_us_submitted",
  NEW_CONTACT_US_ADMIN = "new_contact_us_admin",
  NEW_SESSION_REQUEST = "new_session_request",
  SESSION_REQUEST_ACCEPTED = "session_request_accepted",
  SESSION_REQUEST_REJECTED = "session_request_rejected"
}
